---
- name: Install nopCommerce on ubuntu 
  hosts: all
  become: yes
  tasks:
    - name: Download Microsoft packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp 
    - name: Install Microsoft packages
      dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install 
    - name: Install apt-transport-https and Dotnet 
      apt:
        name:
          - apt-transport-https
          - dotnet-sdk-6.0
        update_cache: yes  
        state: present
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started    
    - name: Create Nginx default configuration
      copy:
        src: default.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644    
    - name: Create nopCommerce directory
      file:
        path: /var/www/nopCommerce
        state: directory
    - name: Download nopCommerce
      get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce/nopCommerce_4.60.1_NoSource_linux_x64.zip   
    - name: extract nopCommerce
      unarchive:
        src: /var/www/nopCommerce/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
    - name: Create bin directory
      file:
        path: /var/www/nopCommerce/bin
        state: directory
    - name: Create logs directory
      file:
        path: /var/www/nopCommerce/logs
        state: directory         