---
- name: Install nopCommerce on ubuntu 
  hosts: all
  become: yes
  tasks:
    - name: Download Microsoft packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp 
    - name: Install Microsoft packages
      dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install 
    - name: Install apt-transport-https and aspnetcore-runtime-7.0
      apt:
        name:
          - apt-transport-https
          - aspnetcore-runtime-7.0
        update_cache: yes  
        state: present
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started    