---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: creating group
      ansible.builtin.group:
        name: tomcat
        state: present    
    - name: creating user
      ansible.builtin.user:
        create_home: true
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        name: tomcat
    - name: download and  extract tomcat
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
        dest: /opt/tomcat      
        remote_src: yes
    - name: creating symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.5
        dest: /opt/tomcat/latest
        state: link
    - name: Change the directory ownership
      ansible.builtin.file:
         path: /opt/tomcat
         state: directory
         recurse: yes
         owner: tomcat
         group: tomcat
    - name: shell scripts inside the Tomcat’s bin directory must be executable
      ansible.builtin.shell: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: creating systemd unit file 
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: reload enabled start 
      ansible.builtin.systemd:
        name: tomcat 
        daemon_reload: true
        enabled: true
        state: started
    - name: copying tomat user files
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml          
    - name: copying manager user files in node 
      ansible.builtin.copy:
        src: managercontext.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml   
    - name: copying hostmanager files in remote node 
      ansible.builtin.copy:
        src: hostcontext.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
    - name: reload enabled start 
      ansible.builtin.systemd:
        name: tomcat 
        daemon_reload: true
        enabled: true
        state: started      