---
# tasks file for ngnixrole
- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Start Nginx
  service:
    name: nginx
    state: started    
- name: Create Nginx default configuration
  copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644  
- name: Restart Nginx
  service:
      name: nginx       