---
# tasks file for ngnixrole
- name: Download Microsoft packages
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp 
- name: Install Microsoft packages
  dpkg_selections:
    name: packages-microsoft-prod.deb
    selection: install 
- name: Install apt-transport-https and Dotnet 
  apt:
    name:
      - apt-transport-https
      - dotnet-sdk-6.0
- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Start Nginx
  service:
    name: nginx
    state: started
- name: Create Nginx default configuration
  copy:
    src: default.conf 
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644  
- name: Restart Nginx
  service:
    name: nginx   
    state: started
      
