---
- name: install nginx
  become: yes
  hosts: webserver
  roles:
    - ngnixrole

- name: install nop
  become: yes
  hosts: appserver
  roles:
    - noprole    

- name: install mysql
  become: yes
  hosts: dbserver
  roles:
    - geerlingguy.mysql