---
- name: install nop
  become: yes
  hosts: appserver
  roles:
    - noprole 

- name: install nginx
  become: yes
  hosts: webserver
  roles:
    - ngnixrole

- name: install nginx
  become: yes
  hosts: dbserver
  roles:
    - ngnixrole   