trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: df -H
  displayName: 'Run Disk utilization'
- script: sudo apt update
  displayName: 'update the packages of ubuntu'
- script: start.sh
  displayName: 'run shell script'