---
- name: install dotnet core 6.0
  become: yes
  hosts: all
  vars:
    dotnet_versions: "6.0"
  tasks:
    - name: Install https
      ansible.builtin.apt:
        name: apt-transport-https
        update_cache: yes 
        state: present   
    - name: Install dotnet core
      ansible.builtin.apt:
        name: dotnet-sdk-{{ dotnet_versions }}
        update_cache: yes 
        state: present
      