---
- name: Install MongoDB
  hosts: webserver
  become: yes
  tasks:  
    - name: copy repository files
      ansible.builtin.copy:
        name: mongodb-org repo file 
        src: mongodb-org.repo
        dest: /etc/yum.repos.d/mongodb-org.repo
    - name: install mongodb-org centos
      yum:
        name: mongodb-org    
        state: present
    - name: start MongoD service
      service:
        name: mongod
        state: started 
        enabled: true
    - name: edited the mogod file
      ansible.builtin.copy:
        src: centosmongod.conf
        dest: /etc/mongod.conf  
    - name: start MongoD service
      service:
        name: mongod
        daemon_reload: yes
        state: started 
        enabled: true    
