---
- name: Install MongoDB
  hosts: webserver
  become: yes
  tasks:
    - name: Add MongoDB GPG key ubuntu 
      apt_key: 
        url: hkp://keyserver.ubuntu.com:80
        id: 9DA31620334BD75D9DCB49F368818C72E52529D4
        state: present
      when:
      - ansible_facts['distribution'] == "Ubuntu"  
    - name: Add MongoDB apt repository ubuntu 
      apt_repository: 
        repo: 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse'
        state: present
      when:
      - ansible_facts['distribution'] == "Ubuntu"
    - name: Add MongoDB yum repository centos 
      yum_repository:
        name: mongodb-org-4.0
        description: MongoDB Repository
        baseurl: 'https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/'
        gpgcheck: 1
        enabled: 1
        gpgkey: https://www.mongodb.org/static/pgp/server-4.o.asc
      when: 
      - - ansible_facts['distribution'] == "CentOS"   
    - name: Update packages and install mongodb ubuntu 
      apt:    
        name: mongodb-org
        update_cache: yes
        state: present
      notify:
      - start MongoD service
      when:
      - ansible_facts['distribution'] == "Ubuntu"  
    - name: install mongodb-org centos
      yum:
        name: mongodb-org
        update_cache: true
        state: present
      notify:
      - start MongoD service
      when: 
      - ansible_facts['distribution'] == "CentOS"   
    - name: edited the mogod file
      ansible.builtin.copy:
        src: mongod.conf
        dest: /etc/mongod.conf
      notify:
      - restart MongoD service    
  handlers:
    - name: start MongoD service
      service:
        name: mongod
        state: started
        enabled: true 
    - name: restart MongoD service
      service:
        name: mongod
        state: restarted  