- name: Install Java
  hosts: all
  become: yes
  tasks:
    - name: Install Java on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: "'Ubuntu' in ansible_facts['distribution']"  
    - name: Install Java on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: "'CentOS' in ansible_facts['distribution']"    