---
- name: jenkins installation
  become: yes
  hosts: all
  tasks: 
    - name: java installation
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: downloading file
      ansible.builtin.get_url:
        url: https://get.jenkins.io/war-stable/2.375.2/
        dest: /home/ubuntu/
    - name: copying service file 
      ansible.builtin.copy:
        src: /home/ubuntu/jenkins.service
        dest: /lib/systemd/system/jenkins.service
        remote_src: true
    - name: service running
      ansible.builtin.systemd:
        name: jenkins.service 
        enabled: yes
        state: started