---
- name: install nodejs
  become: yes
  hosts: all
  tasks:
    - name: Install Node package manager and Nodejs on Ubuntu.
      ansible.builtin.apt:
        name: 
         - npm
         - nodejs
        update_cache: yes 
        state: present
      when: "'Ubuntu' in ansible_facts['distribution']"   
    - name: Add NodeSource repository 
      ansible.builtin.command: https://rpm.nodesource.com/setup_10.x
        update_cache: yes 
        state: present    
      when: "'CentOS' in ansible_facts['distribution']"    
    - name: install nodejs on centos 
      ansible.builtin.yum:
        name: nodejs
        update_cache: yes 
        state: present   
      when: "'CentOS' in ansible_facts['distribution']"     

