---
- name: install nodejs
  become: yes
  hosts: all
  tasks:
    - name: Install nodejs and npm 
      ansible.builtin.apt:
        name: 
         - nodejs
         - npm
        update_cache: yes 
        state: present
    - name: NodeSource installation
      ansible.builtin.uri:
        url: https://deb.nodesource.com/setup_18.x