---
- name: install nodejs
  hosts: all
  become: yes
  tasks:
    - name: Install Node package manager and Nodejs on Ubuntu.
      ansible.builtin.apt:
        name: 
         - npm
         - nodejs
        update_cache: true
        state: present
      when: "'Ubuntu' in ansible_facts['distribution']"
    - name: update cache
      yum: 
        update_cache: true
      when: "'CentOS' in ansible_facts['distribution']"  
    - name: Add NodeSource repository 
      yum_repository:
        name: nodesource
        description: Node.js Packages
        baseurl: https://rpm.nodesource.com/pub_14.x/el/7/$basearch
        gpgcheck: yes
      when: "'CentOS' in ansible_facts['distribution']"    
    - name: install node.js on centos 
      yum:
        name: nodejs
        state: present   
      when: "'CentOS' in ansible_facts['distribution']"     

