---
- name: install dotnet core 6.0
  become: yes
  hosts: all
  vars:
    dotnet_versions: "6.0"
    openjdk_versions: "11"
  tasks:
    - name: Install https
      ansible.builtin.apt:
        name: apt-transport-https
        update_cache: yes 
        state: present   
      when: ansible_facts[]  
    - name: Install dotnet core
      ansible.builtin.apt:
        name: dotnet-sdk-{{ dotnet_versions }}
        update_cache: yes 
        state: present
    - name: Install java
      ansible.builtin.apt:
        name: openjdk-{{ openjdk_versions }}-jdk
        update_cache: yes 
        state: present    
    - name: Install nodejs and npm 
      ansible.builtin.apt:
        name: 
         - nodejs
         - npm
        update_cache: yes 
        state: present    
        
        
        
      